### ISSUE TITLE
Only work on empty editor?

### ISSUE THREAD

**Issue by Seb33300** [radpet/ckeditor-layoutmanager#10]
Hi,

Your plugins seem to not be working properly if the editor is initialized with content.

I can add a new grid, but grids I previously created are not properly displayed.

Can you confirm that?

Thanks

**Comment by radpet** [comment]
Hello,
What should not properly displayed refer to? What is the content it is
initialized with.

**Comment by radpet** [comment]
should be fixed with commiting : https://github.com/radpet/ckeditor-layoutmanager/commit/1f7b526acbe7339f91b01abad1391c81a5206a10
