### ISSUE TITLE
Issue with duplicate classes

### ISSUE THREAD

**Issue by brandonneil** [radpet/ckeditor-layoutmanager#11]
Hello,

I'm currently having an issue where specific classes are being duplicated. Specifically container-fluid and row classes are being duplicated each time I save content.

I know this is vague - what other information could I provide to help solve the issue.

I'm loading CKEditor into the Drupal CMS, but everything is on the Drupal-side seems to be saving normally.

**Comment by radpet** [comment]
Would you send me some logs (the dom tree before save and after save for example)

**Comment by brandonneil** [comment]
I did figure out that this was an issue with the CMS all along. Sorry!

**Comment by peaton13** [comment]
brandonneil, what was the issue with the CMS? I'm seeing the same thing happen in Drupal. Thanks!

**Comment by brandonneil** [comment]
@peaton13 for me, it was that I had duplicate (container-fluid, row) classes listed in the Rules for Class Names section of the wysiwyg_filter text filter settings. Clearing out those from the configuration no longer exponentially duplicated the classes.

**Comment by peaton13** [comment]
@brandonneil - That was it! I had both "image-inline" and "image-" (with trailing asterisks) in the Rules for Class Names, just far enough apart not to see them both at the same time. Thanks so much!!!
