### ISSUE TITLE
Missing Release

### ISSUE THREAD

**Issue by ChuChuNaKu** [radpet/ckeditor-layoutmanager#15]
Hello @radpet. First let me start by expressing how grateful I am for your outstanding work on this CKEditor plugin. Fantastic job! I'm in the process of writing a Drupal 8 CKEditor module that will use the ckeditor-layoutmanager plugin and was wondering if have any plans on adding a release for ckeditor-layoutmanager?

I ask because in order to complete my Drupal module I'll need to reference the ckeditor-layoutmanager plugin by a tagged release. But unfortunately there aren't any releases yet for the plugin https://github.com/radpet/ckeditor-layoutmanager/releases

**Comment by radpet** [comment]
Hi @ChuChuNaKu I have tagged a release for you https://github.com/radpet/ckeditor-layoutmanager/releases/tag/v1 :). Feel free to use it and report issues if any. I no longer maintain the plugin codebase but you can freely send pull requests.

**Comment by ChuChuNaKu** [comment]
Thanks so much for your help @radpet !!
