### ISSUE TITLE
Can't download basewidget?

### ISSUE THREAD

**Issue by Adel-Magebinary** [radpet/ckeditor-layoutmanager#2]
Hi Team,

base widget seems to be 404 now?

http://ckeditor.com/addon/basewidget

**Comment by radpet** [comment]
Hello,
Yea it seems the basewidget plugin have been removed somehow.. I will reupload it

**Comment by brandonneil** [comment]
@radpet will you be releasing basewidget on github.com for community contribution?

**Comment by radpet** [comment]
Okey no problem I will set up repo tomorrow.
