### ISSUE TITLE
Integrating Layoutmanager with Backbone.js based application

### ISSUE THREAD

**Issue by darkwiz** [radpet/ckeditor-layoutmanager#7]
Hi,
i found your plugin very useful, you did a great job! For my needs would be nice if i could add rows bypassing the button on the toolbar, i'm using your plugin with a backbone app and i need to add a few rows at once. Does the plugin have a minimal api that could be used in this way or there's a workaround to do that?

**Comment by radpet** [comment]
Hello,
Well the plugin registers widgets with all the types of layouts. So if you want to insert a special type of grid without using the dialog window you can do  editor.execCommand(gridType)

List of grid types:
"12" , "6/6", "9/3", "3/9", "8/4", "4/8", "7/5", "5/7", "4/4/4","6/3/3", "3/6/3", "3/3/6";

I hope that works for you :).
I am waiting for your response.

**Comment by darkwiz** [comment]
Awesome, it works perfectly, easy and sleek!
I was trying to use basewidget method "addWidget" but i couldn't make it work properly.
Thank you very much for the quick response, i hope i can help you back soon!
