### ISSUE TITLE
Problem logging from plugin

### ISSUE THREAD

**Issue by darkwiz** [radpet/ckeditor-layoutmanager#9]
Hello radpet,
i want to say thank you again for your excelent work.
I don't know if it's a bug, but i cannot log anything from plugin.js. I would like to understand better how the plugin works in order to extend its features. As an example i would like to have the possibility to add other css selectors(classes, id) to the widget template dinamically but in order to do so it would be nice if the command "gridType" could support optional data as parameters, e.g.:

`editor.execCommand(gridType, [options])`

Thank you again.

**Comment by radpet** [comment]
Hello thanks for your feedback,
It is not currently available and it will need some more code to be written. I'll rewrite the whole plugin soon and will include it as functionality.

I will be happy to hear more suggestions for features :).
